{"FileAddress":null,"Exception":{"ClassName":"System.NullReferenceException","Message":"Object reference not set to an instance of an object.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Geeks.GeeksProductivityTools.Menus.Cleanup.Renamer.<GetNewStartNodeAsync>d__21.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Geeks.GeeksProductivityTools.Menus.Cleanup.Renamer.<RenameSymbolAsync>d__20.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Geeks.GeeksProductivityTools.Menus.Cleanup.Renamer.<RenameSymbolAsync>d__23.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Geeks.GeeksProductivityTools.Menus.Cleanup.Renamer.<RenameIdentifierOfContainerNodeAsync>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Geeks.GeeksProductivityTools.Menus.Cleanup.Renamer.<RenameDeclarationNodeOfContainerNodeAsync>d__8.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Geeks.GeeksProductivityTools.Menus.Cleanup.Renamer.<RenameDeclarationsAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Geeks.VSIX.TidyCSharp.Cleanup.CamelCasedFields.Rewriter.<RenameDeclarationsAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Geeks.VSIX.TidyCSharp.Cleanup.CamelCasedFields.Rewriter.<>c__DisplayClass1_0.<<VisitClassDeclaration>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()\r\n   at Geeks.VSIX.TidyCSharp.Cleanup.CamelCasedFields.Rewriter.VisitClassDeclaration(ClassDeclarationSyntax node)\r\n   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)\r\n   at Geeks.GeeksProductivityTools.Menus.Cleanup.VariableRenamingBase.<CleanUpAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Geeks.GeeksProductivityTools.Menus.Cleanup.CodeCleanerCommandRunnerBase.<RunAsync>d__15.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nMoveNext\nGeeksVSIX.TidyCSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6488799cafd93a4a\nGeeks.GeeksProductivityTools.Menus.Cleanup.Renamer+<GetNewStartNodeAsync>d__21\nVoid MoveNext()","HResult":-2147467261,"Source":"GeeksVSIX.TidyCSharp","WatsonBuckets":null}}